### ISSUE TITLE
CASTLEGUARD - Basis

### ISSUE THREAD

**Issue by Ralfons-06** [fjoniyz/ganges#32]
Base Skeleton for Algorithm:

**Definition (Differentially Private k-anonymity in Data
Streams).** _Algorithm A satisfies differentially private k-
anonymity over an arbitrary input data stream D if:_

   - **β-Sampling:** When D yields a tuple it is immediately suppressed with probability 1 − β
   - **Perturbation:** Sampled tuples have their QI values perturbed using additive noise and are grouped using generalized clusters over perturbed values
   - **k-Suppression:** Generalisations are suppressed (not published) if they appear less than k times
 

![image](https://github.com/fjoniyz/ganges/assets/68425676/e48d2170-910a-45f4-8ae5-714064623f53)

[Reference](https://github.com/hallnath1/CASTLEGUARDl)

## Tasks

- [x] Initialization of Castle Algorithm with respective Parameters
- [x] Base ("controller") for the algorithm (see **pseudocode** and `insert()` method in `castle.py`)
- [x] Random omission of a data point (β-sampling)
- [x] Adding a data point to a cluster
- [x] Output of a cluster + delay constraint
     - [x] In conjunction with Cluster Operations Team → publish clusters as small as possible 
- [x] Interface for Perturbation, Best Selection
